### ISSUE TITLE
Node crash after Request Funds

### ISSUE THREAD

**Issue by mstrewe** [Dr-Electron/ElectricShimmer#1]
I freshly installed lates Version of the wallet (0.1.2) (Precompiled from release page).
Then I updated node IP to my node (0.2.3) (node is in sync) (success)
Then I generated a new seed (success)
Then I requested funds (success)
Then I navigated to Dashboard. (success) But no balance was shown (I think it was still pending)
Then I selected "Adresses" and the Wallet was closed by a crash. 

Eventlog:
```
Anwendung: ElectricShimmer.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.FormatException
   bei System.Number.StringToNumber(System.String, System.Globalization.NumberStyles, NumberBuffer ByRef, System.Globalization.NumberFormatInfo, Boolean)
   bei System.Number.ParseInt64(System.String, System.Globalization.NumberStyles, System.Globalization.NumberFormatInfo)
   bei ElectricShimmer.ViewModel.WalletViewModel+<>c__DisplayClass68_0.<UpdateBalance>b__2(System.Object, System.EventArgs)
   bei System.Diagnostics.Process.OnExited()
   bei System.Diagnostics.Process.RaiseOnExited()
   bei System.Diagnostics.Process.CompletionCallback(System.Object, Boolean)
   bei System.Threading._ThreadPoolWaitOrTimerCallback.WaitOrTimerCallback_Context(System.Object, Boolean)
   bei System.Threading._ThreadPoolWaitOrTimerCallback.WaitOrTimerCallback_Context_f(System.Object)
   bei System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading._ThreadPoolWaitOrTimerCallback.PerformWaitOrTimerCallback(System.Object, Boolean)
```

I tried to start the wallet again but it crashes again with same error.

Wallet log:

[ElectricShimmer.log](https://github.com/Dr-Electron/ElectricShimmer/files/5061264/ElectricShimmer.log)

**Comment by Dr-Electron** [comment]
I'm not sure if this is a bug on my side. Could you try `.\cli-wallet balance`? There probably is a letter in the balance column. I already found this bug in the last cli release but couldn`t open an issue, as they did reset the network with the newest release and i couldn't reproduce it anymore
